<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">

    <xacro:include filename="inertial_macros.xacro"/>

      <!-- Chassis parameters -->
      <xacro:property name="chassis_length" value="0.36"/>
      <xacro:property name="chassis_width" value="0.3"/>
      <xacro:property name="chassis_height" value="0.33"/>
      <xacro:property name="chassis_mass" value="1.0"/>
    
      <!-- Wheel parameters -->
      
      <xacro:property name="wheel_radius" value="0.03"/>
      <xacro:property name="wheel_thickness" value="0.04"/>
      <xacro:property name="wheel_mass" value="0.05"/>
      
      <xacro:property name="wheel_offset_x" value="0.356"/>
      <xacro:property name="wheel_offset_y" value="0.330"/>
      <xacro:property name="wheel_offset_z" value="0.01"/>
      
      <xacro:property name="mesh_chassis_z" value="-0.015"/>
      <xacro:property name="PI" value="3.1415926535897931" />
      <!-- Simple Macro to calculate inertia -->
      

      <!--COLOR_RVIZ-->
    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>
    
    <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>

     <!-- BASE LINK -->

     <link name="base_link">

     </link>
 
     <!-- BASE_FOOTPRINT LINK -->
 
     <joint name="base_footprint_joint" type="fixed">
         <parent link="base_link"/>
         <child link="base_footprint"/>
         <origin xyz="0 0 0" rpy="0 0 0"/>
     </joint>
 
     <link name="base_footprint">
     </link>


     <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis">

        <visual>
            <origin xyz="${chassis_length/2} 0 ${mesh_chassis_z}" rpy="0 0 0"/>
            <geometry>
                <mesh filename="/my_src/golf_kart/golf_kart/meshes/golf_kart.stl" scale="1 1 1"/>
            </geometry>
            <material name="gray"/>
            
        </visual>

        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="0.5" x="0.3" y="0.3" z="0.15">
            <origin xyz="0.15 0 0.075" rpy="0 0 0"/>
        </xacro:inertial_box>

    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Whitek</material>
    </gazebo>



     <!-- REAR LEFT WHEEL LINK -->

     <!-- <joint name="rear_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_left_wheel"/>
        <origin xyz="${chassis_length/4 + wheel_radius} ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint> -->

    <link name="rear_left_wheel">
       
        <collision>
            <geometry>
                 <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="rear_left_wheel">
        <material>Gazebo/Blue</material>
        <mu1 value="1.0"/>
		<mu2 value="1.0"/>
		<kp value="10000000.0" />
		<kd value="1.0" />
		<fdir1 value="1 0 0"/>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>




    <!-- REAR RIGHT WHEEL LINK -->

    <!-- <joint name="rear_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="rear_right_wheel"/>
        <origin xyz="${chassis_length/4 + wheel_radius} ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint> -->

    <link name="rear_right_wheel">
      

        <collision>
            <geometry>
                 <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    
    </link>

    <gazebo reference="rear_right_wheel">
        <material>Gazebo/Blue</material>
        <mu1 value="1.0"/>
		<mu2 value="1.0"/>
		<kp value="10000000.0" />
		<kd value="1.0" />
		<fdir1 value="1 0 0"/>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>



 <!-- FRONT LEFT WHEEL LINK -->

 <joint name="front_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_left_wheel"/>
    <origin xyz="${-(wheel_offset_x+wheel_radius/2)} ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
    <axis xyz="0 0 1"/>
</joint>

<link name="front_left_wheel">
  

    <collision>
        <geometry>
             <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
    </collision>

    <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
 
</link>

<gazebo reference="front_left_wheel">
    <material>Gazebo/Blue</material>
    <mu1 value="1.0"/>
		<mu2 value="1.0"/>
		<kp value="10000000.0" />
		<kd value="1.0" />
		<fdir1 value="1 0 0"/>
        <turnGravityOff>false</turnGravityOff>
</gazebo>




<!-- FRONT RIGHT WHEEL LINK -->

<joint name="front_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_right_wheel"/>
    <origin xyz="${-(wheel_offset_x+wheel_radius/2)} ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
    <axis xyz="0 0 -1"/>
</joint>

<link name="front_right_wheel">
    

    <collision>
        <geometry>
             <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
    </collision>

    <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>

</link>

<gazebo reference="front_right_wheel">
    <material>Gazebo/Blue</material>
    <mu1 value="1.0"/>
		<mu2 value="1.0"/>
		<kp value="10000000.0" />
		<kd value="1.0" />
		<fdir1 value="1 0 0"/>
        <turnGravityOff>false</turnGravityOff>
</gazebo>

            <!-- STEERING -->



<link name="steering_wheel">
    <collision>
        <geometry>
             <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
    </collision>

    <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>

            
</link>


<joint name="steering_joint" type="revolute">
    <parent link="chassis"/>
    <child link="steering_wheel"/>
    <origin xyz="-0.002 0 0" rpy="${pi/2} 0 0" />
    <axis xyz="0 0.964095 0.265556"/>
    <limit lower="-7.85" upper="7.85" effort="10" velocity="1"/>
</joint>

<!-- REAR AXLE -->

<link name="rear_axle">
    <collision>
        <geometry>
             <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
    </collision>

    <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>

            
</link>


<joint name="rear_axle_joint" type="revolute">
    <parent link="chassis"/>
    <child link="rear_axle"/>
    <origin xyz="-0.002 0 0" rpy="${pi/2} 0 0" />
    <axis xyz="0 0.964095 0.265556"/>
    <limit lower="-7.85" upper="7.85" effort="10" velocity="1"/>
</joint>

<joint name="rear_left_wheel_joint" type="continuous">
    <parent link="rear_axle"/>
    <child link="rear_left_wheel"/>
    <origin xyz="${chassis_length/4 + wheel_radius} ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
    <axis xyz="0 0 1"/>
</joint>

<joint name="rear_right_wheel_joint" type="continuous">
    <parent link="rear_axle"/>
    <child link="rear_right_wheel"/>
    <origin xyz="${chassis_length/4 + wheel_radius} ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
    <axis xyz="0 0 -1"/>
</joint>
    
</robot>